$CONFIGID= 'XXXXXXX'
$APITOKEN='XXXXXX-XXXXXX'
$ASSIGNMENTOPTIONS= '"--grant-easy-access"'

msiexec.exe /i "\\$SHARE\$PATH\TeamViewer_Host.msi" /qn CUSTOMCONFIGID=$CONFIGID APITOKEN=$APITOKEN ASSIGNMENTOPTIONS=$ASSIGNMENTOPTIONS
